### ISSUE TITLE
Try to export a PieCharts to XLSX

### ISSUE THREAD

**Issue by reiniermujica** [chris-vecchio/export-xlsx-exceljs#2]
I found a bug in my company software, when the client try to export a PieCharts to XLSX, the export sheet only contains the first row of the data.

The data is in this format: 
[
  {
    "name": "Brands",
    "colorByPoint": true,
    "data": [
      {
        "name": "Chrome",
        "y": 61.41,
        "sliced": true,
        "selected": true
      },
      {
        "name": "Internet Explorer",
        "y": 11.84
      },
      {
        "name": "Firefox",
        "y": 10.85
      }
]

I finally found that the problem was in this function: https://github.com/highcharts/highcharts/issues/7913#issuecomment-371052869

When the data is filtering. I removed the function and the export success.

**Comment by chris-vecchio** [comment]
Hi! @reiniermujica Thanks for reporting this. I have a feeling the issue stems from how the filtering function interacts with certain series types. I'll see if I can figure out a solution outside of providing users an option to disable the filtering function.

**Comment by chris-vecchio** [comment]
Sorry for the delayed reply. I just pushed a new version that automatically disables data row filtering for Pie charts as well as several other updates.

**Comment by chris-vecchio** [comment]
@reiniermujica Closing since I believe I have addressed your issue. Feel free to open another if I haven't.
